/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package megacasting.ihm;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import megacasting.dao.DomaineMetierDAO;
import megacasting.dao.MetierDAO;
import megacasting.entite.DomaineMetier;
import megacasting.entite.Metier;

/**
 *
 * @author MAXIME
 */
public class ajouterMetierFrame extends javax.swing.JFrame {

    /**
     * Creates new form ajouterMetierFrame
     */
    public ajouterMetierFrame() {
        initComponents();
        
        refreshComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAjouterMetier = new javax.swing.JPanel();
        labelLibelle = new javax.swing.JLabel();
        labelDomaine = new javax.swing.JLabel();
        textFieldLibelle = new javax.swing.JTextField();
        comboBoxDomaine = new javax.swing.JComboBox();
        buttonAjouterMetier = new javax.swing.JButton();
        labelTitreFrame = new javax.swing.JLabel();

        panelAjouterMetier.setBackground(new java.awt.Color(153, 153, 153));

        labelLibelle.setText("Libellé");

        labelDomaine.setText("Domaine");

        comboBoxDomaine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonAjouterMetier.setText("Ajouter");
        buttonAjouterMetier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterMetierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAjouterMetierLayout = new javax.swing.GroupLayout(panelAjouterMetier);
        panelAjouterMetier.setLayout(panelAjouterMetierLayout);
        panelAjouterMetierLayout.setHorizontalGroup(
            panelAjouterMetierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjouterMetierLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelAjouterMetierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonAjouterMetier)
                    .addGroup(panelAjouterMetierLayout.createSequentialGroup()
                        .addGroup(panelAjouterMetierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDomaine))
                        .addGap(33, 33, 33)
                        .addGroup(panelAjouterMetierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldLibelle)
                            .addComponent(comboBoxDomaine, 0, 99, Short.MAX_VALUE))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        panelAjouterMetierLayout.setVerticalGroup(
            panelAjouterMetierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjouterMetierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAjouterMetierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLibelle)
                    .addComponent(textFieldLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAjouterMetierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDomaine)
                    .addComponent(comboBoxDomaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonAjouterMetier)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelTitreFrame.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitreFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitreFrame.setText("Ajouter un métier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(labelTitreFrame))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(panelAjouterMetier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(labelTitreFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAjouterMetier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAjouterMetierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterMetierActionPerformed
        Metier m = new Metier();
        m.setLibelle(textFieldLibelle.getText());
        DomaineMetier dm = (DomaineMetier) comboBoxDomaine.getSelectedItem();
        m.setIdDomaineMetier(dm.getId());
        
        try {
            MetierDAO.creer(mainFrame.cnx, m);
            JOptionPane.showMessageDialog(panelAjouterMetier,"L'ajout a été réussie");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(panelAjouterMetier, ex.toString());
        }
        this.dispose();
    }//GEN-LAST:event_buttonAjouterMetierActionPerformed

    private void refreshComboBox(){
        DefaultComboBoxModel<DomaineMetier> comboBoxDomaineMetierModel = new DefaultComboBoxModel<>();
        comboBoxDomaine.setModel(comboBoxDomaineMetierModel);
        
        DefaultComboBoxModel<DomaineMetier> comboBoxModel = (DefaultComboBoxModel<DomaineMetier>) comboBoxDomaine.getModel();
        
        List<DomaineMetier> ldomaineMetiers = DomaineMetierDAO.lister(mainFrame.cnx);
        
        for(DomaineMetier dm : ldomaineMetiers){
            comboBoxModel.addElement(dm);
        }
        comboBoxDomaine.setModel(comboBoxModel);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouterMetierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouterMetierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouterMetierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouterMetierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajouterMetierFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjouterMetier;
    private javax.swing.JComboBox comboBoxDomaine;
    private javax.swing.JLabel labelDomaine;
    private javax.swing.JLabel labelLibelle;
    private javax.swing.JLabel labelTitreFrame;
    private javax.swing.JPanel panelAjouterMetier;
    private javax.swing.JTextField textFieldLibelle;
    // End of variables declaration//GEN-END:variables
}
