/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package megacasting.ihm;

import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import megacasting.dao.AnnonceurDAO;
import megacasting.dao.DomaineMetierDAO;
import megacasting.dao.MetierDAO;
import megacasting.dao.OffreDAO;
import megacasting.dao.SocieteDAO;
import megacasting.dao.TypeContratDAO;
import megacasting.entite.Annonceur;
import megacasting.entite.DomaineMetier;
import megacasting.entite.Metier;
import megacasting.entite.Offre;
import megacasting.entite.Societe;
import megacasting.entite.TypeContrat;

/**
 *
 * @author ihamel
 */
public class ajouterOffreFrame extends javax.swing.JFrame {

    /**
     * Creates new form ajouterOffreFrame
     */
    public ajouterOffreFrame() {
        initComponents();
        refreshComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAjoutOffre = new javax.swing.JPanel();
        labelIntitule = new javax.swing.JLabel();
        labelReference = new javax.swing.JLabel();
        labelDatePublication = new javax.swing.JLabel();
        labelDureeDiffusion = new javax.swing.JLabel();
        labelDateDebutContrat = new javax.swing.JLabel();
        labelNbPoste = new javax.swing.JLabel();
        labelLocalisation = new javax.swing.JLabel();
        labelDescriptionPoste = new javax.swing.JLabel();
        labelDescriptionProfil = new javax.swing.JLabel();
        labelTelephone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelTypeContrat = new javax.swing.JLabel();
        labelMetier = new javax.swing.JLabel();
        labelDomaineMetier = new javax.swing.JLabel();
        labelAnnonceur = new javax.swing.JLabel();
        textFieldIntitule = new javax.swing.JTextField();
        textFieldReference = new javax.swing.JTextField();
        textFieldLocalisation = new javax.swing.JTextField();
        textFieldEmail = new javax.swing.JTextField();
        textFieldTelephone = new javax.swing.JTextField();
        comboBoxNombrePoste = new javax.swing.JComboBox();
        labelJour = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescriptionPoste = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDescriptionProfil = new javax.swing.JTextArea();
        spinnerDureeDiffusion = new javax.swing.JSpinner();
        buttonAjouterOffre = new javax.swing.JButton();
        comboBoxMetier = new javax.swing.JComboBox();
        comboBoxTypeContrat = new javax.swing.JComboBox();
        comboBoxAnnonceur = new javax.swing.JComboBox();
        comboBoxDomaineMetier = new javax.swing.JComboBox();
        dateChooserPublication = new com.toedter.calendar.JDateChooser();
        dateChooserDebutContrat = new com.toedter.calendar.JDateChooser();
        labelAjouterOffre = new javax.swing.JLabel();

        panelAjoutOffre.setBackground(new java.awt.Color(153, 153, 153));

        labelIntitule.setText("Intitule");

        labelReference.setText("Référence");

        labelDatePublication.setText("Date de publication");

        labelDureeDiffusion.setText("Durée de diffusion");

        labelDateDebutContrat.setText("Date du début du contrat");

        labelNbPoste.setText("Nombre de poste");

        labelLocalisation.setText("Localisation");

        labelDescriptionPoste.setText("Description du poste");

        labelDescriptionProfil.setText("Description du profil");

        labelTelephone.setText("Numéro de téléphone");

        labelEmail.setText("Email");

        labelTypeContrat.setText("Type de contrat");

        labelMetier.setText("Métier");

        labelDomaineMetier.setText("Domaine de métier");

        labelAnnonceur.setText("Annonceur");

        labelJour.setText("Jour(s)");

        textAreaDescriptionPoste.setColumns(20);
        textAreaDescriptionPoste.setRows(5);
        jScrollPane1.setViewportView(textAreaDescriptionPoste);

        textAreaDescriptionProfil.setColumns(20);
        textAreaDescriptionProfil.setRows(5);
        jScrollPane2.setViewportView(textAreaDescriptionProfil);

        buttonAjouterOffre.setText("Ajouter");
        buttonAjouterOffre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterOffreActionPerformed(evt);
            }
        });

        comboBoxDomaineMetier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelAjoutOffreLayout = new javax.swing.GroupLayout(panelAjoutOffre);
        panelAjoutOffre.setLayout(panelAjoutOffreLayout);
        panelAjoutOffreLayout.setHorizontalGroup(
            panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjoutOffreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAjoutOffreLayout.createSequentialGroup()
                        .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTelephone)
                            .addComponent(labelDescriptionProfil)
                            .addComponent(labelDescriptionPoste)
                            .addComponent(labelLocalisation)
                            .addComponent(labelNbPoste)
                            .addComponent(labelDateDebutContrat)
                            .addComponent(labelDureeDiffusion)
                            .addComponent(labelDatePublication)
                            .addComponent(labelReference)
                            .addComponent(labelIntitule))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAjoutOffreLayout.createSequentialGroup()
                                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(textFieldLocalisation)
                                    .addComponent(textFieldIntitule)
                                    .addComponent(textFieldReference, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelAjoutOffreLayout.createSequentialGroup()
                                        .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateChooserPublication, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(panelAjoutOffreLayout.createSequentialGroup()
                                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonAjouterOffre)
                                    .addComponent(comboBoxNombrePoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelAjoutOffreLayout.createSequentialGroup()
                                        .addComponent(spinnerDureeDiffusion, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelJour))
                                    .addComponent(comboBoxAnnonceur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateChooserDebutContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelAjoutOffreLayout.createSequentialGroup()
                        .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDomaineMetier)
                            .addComponent(labelAnnonceur)
                            .addGroup(panelAjoutOffreLayout.createSequentialGroup()
                                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTypeContrat))
                                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAjoutOffreLayout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelAjoutOffreLayout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboBoxMetier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboBoxTypeContrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboBoxDomaineMetier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(labelMetier, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelAjoutOffreLayout.setVerticalGroup(
            panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjoutOffreLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIntitule)
                    .addComponent(textFieldIntitule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelReference)
                    .addComponent(textFieldReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDatePublication)
                    .addComponent(dateChooserPublication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDureeDiffusion)
                    .addComponent(labelJour)
                    .addComponent(spinnerDureeDiffusion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDateDebutContrat)
                    .addComponent(dateChooserDebutContrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNbPoste)
                    .addComponent(comboBoxNombrePoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLocalisation)
                    .addComponent(textFieldLocalisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescriptionPoste))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescriptionProfil))
                .addGap(6, 6, 6)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelephone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTypeContrat)
                    .addComponent(comboBoxTypeContrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxMetier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDomaineMetier)
                    .addComponent(comboBoxDomaineMetier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAjoutOffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAnnonceur)
                    .addComponent(comboBoxAnnonceur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonAjouterOffre)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        labelAjouterOffre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAjouterOffre.setText("Ajouter une offre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panelAjoutOffre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelAjouterOffre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelAjouterOffre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAjoutOffre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAjouterOffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterOffreActionPerformed
        Offre o = new Offre();

        o.setIntitule(textFieldIntitule.getText());
        o.setReference(textFieldReference.getText());
        // Date publication
        Date publication = dateChooserPublication.getDate();
        o.setDatePublication(publication);
        o.setDureeDiffusion((int) spinnerDureeDiffusion.getValue());
        // Date Debut Contrat
        Date debutContrat = dateChooserDebutContrat.getDate();
        o.setDateDebutContrat(debutContrat);
        o.setNbPostes((int) comboBoxNombrePoste.getSelectedItem());
        o.setLocalisation(textFieldLocalisation.getText());
        o.setDescriptionPoste(textAreaDescriptionPoste.getText());
        o.setDescriptionProfil(textAreaDescriptionPoste.getText());
        o.setTelephone(textFieldTelephone.getText());
        o.setMail(textFieldEmail.getText());
        // Type Contrat
        String libelleTempTC = (String) comboBoxTypeContrat.getSelectedItem();
        TypeContrat tc = TypeContratDAO.trouver(mainFrame.cnx, libelleTempTC);
        if(tc != null){
            o.setIdTypeContrat(tc.getId());
        }

        // Metier
        String libelleTempM = (String) comboBoxMetier.getSelectedItem();
        Metier m = MetierDAO.trouver(mainFrame.cnx, libelleTempM);
        if(m != null){
            o.setIdMetier(m.getId());
        }
        // Domaine metier
        String libelleTempDM = (String) comboBoxDomaineMetier.getSelectedItem();
        DomaineMetier dm = DomaineMetierDAO.trouver(mainFrame.cnx, libelleTempDM);
        if(dm != null){
            o.setIdDomaineMetier(dm.getId());
        }

        // Annonceur
        String libelleTempA = (String) comboBoxAnnonceur.getSelectedItem();
        Societe s = SocieteDAO.trouver(mainFrame.cnx,libelleTempA);
        if(s != null){
            Annonceur a = AnnonceurDAO.trouver(mainFrame.cnx, s.getId());
            if(a != null){
                o.setIdAnnonceur(a.getId());
            }
        }

        try {
            OffreDAO.creer(mainFrame.cnx, o);
            JOptionPane.showMessageDialog(panelAjoutOffre, "L'offre a bien été ajoutée ");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(panelAjoutOffre, ex.toString());
        }
    }//GEN-LAST:event_buttonAjouterOffreActionPerformed

    private void refreshComboBox() {

        // Nombre de postes
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
        for (int i = 1; i < 11; i++) {
            comboBoxModel.addElement(i);
        }
        comboBoxNombrePoste.setModel(comboBoxModel);

        // TypeContrat
        DefaultComboBoxModel comboBoxModelTypeContrat = new DefaultComboBoxModel();
        List<TypeContrat> lTypeContrat = TypeContratDAO.lister(mainFrame.cnx);
        for (TypeContrat tc : lTypeContrat) {
            comboBoxModelTypeContrat.addElement(tc.getLibelle());
        }
        comboBoxTypeContrat.setModel(comboBoxModelTypeContrat);

        // Metier
        DefaultComboBoxModel comboBoxModelMetier = new DefaultComboBoxModel();
        List<Metier> lMetier = MetierDAO.lister(mainFrame.cnx);
        for (Metier m : lMetier) {
            comboBoxModelMetier.addElement(m.getLibelle());
        }
        comboBoxMetier.setModel(comboBoxModelMetier);

        // Domaine Metier
        DefaultComboBoxModel comboBoxModelDomaineMetier = new DefaultComboBoxModel();
        List<DomaineMetier> lDomaineMetier = DomaineMetierDAO.lister(mainFrame.cnx);
        for (DomaineMetier dm : lDomaineMetier) {
            comboBoxModelDomaineMetier.addElement(dm.getLibelle());
        }
        comboBoxDomaineMetier.setModel(comboBoxModelDomaineMetier);

        // Annonceur
        DefaultComboBoxModel comboBoxModelAnnonceur = new DefaultComboBoxModel();
        List<Annonceur> lAnnonceur = AnnonceurDAO.lister(mainFrame.cnx);
        for (Annonceur a : lAnnonceur) {
            Societe s = SocieteDAO.trouver(mainFrame.cnx, a.getId());
            comboBoxModelAnnonceur.addElement(s.getRaisonSociale());
        }
        comboBoxAnnonceur.setModel(comboBoxModelAnnonceur);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouterOffreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouterOffreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouterOffreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouterOffreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajouterOffreFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjouterOffre;
    private javax.swing.JComboBox comboBoxAnnonceur;
    private javax.swing.JComboBox comboBoxDomaineMetier;
    private javax.swing.JComboBox comboBoxMetier;
    private javax.swing.JComboBox comboBoxNombrePoste;
    private javax.swing.JComboBox comboBoxTypeContrat;
    private com.toedter.calendar.JDateChooser dateChooserDebutContrat;
    private com.toedter.calendar.JDateChooser dateChooserPublication;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAjouterOffre;
    private javax.swing.JLabel labelAnnonceur;
    private javax.swing.JLabel labelDateDebutContrat;
    private javax.swing.JLabel labelDatePublication;
    private javax.swing.JLabel labelDescriptionPoste;
    private javax.swing.JLabel labelDescriptionProfil;
    private javax.swing.JLabel labelDomaineMetier;
    private javax.swing.JLabel labelDureeDiffusion;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelIntitule;
    private javax.swing.JLabel labelJour;
    private javax.swing.JLabel labelLocalisation;
    private javax.swing.JLabel labelMetier;
    private javax.swing.JLabel labelNbPoste;
    private javax.swing.JLabel labelReference;
    private javax.swing.JLabel labelTelephone;
    private javax.swing.JLabel labelTypeContrat;
    private javax.swing.JPanel panelAjoutOffre;
    private javax.swing.JSpinner spinnerDureeDiffusion;
    private javax.swing.JTextArea textAreaDescriptionPoste;
    private javax.swing.JTextArea textAreaDescriptionProfil;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldIntitule;
    private javax.swing.JTextField textFieldLocalisation;
    private javax.swing.JTextField textFieldReference;
    private javax.swing.JTextField textFieldTelephone;
    // End of variables declaration//GEN-END:variables
}
