/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package megacasting.ihm;

import javax.swing.JOptionPane;
import megacasting.dao.AnnonceurDAO;
import megacasting.dao.SocieteDAO;
import megacasting.entite.Annonceur;
import megacasting.entite.Societe;

/**
 *
 * @author MAXIME
 */
public class ajouterAnnonceurFrame extends javax.swing.JFrame {

    /**
     * Creates new form ajouterAnnonceurFrame
     */
    public ajouterAnnonceurFrame() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAnnonceur = new javax.swing.JPanel();
        buttonAjouterAnnonceur = new javax.swing.JButton();
        labelRaisonSociale = new javax.swing.JLabel();
        labelTelephone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelAdresse = new javax.swing.JLabel();
        labelSiret = new javax.swing.JLabel();
        textFieldRaisonSociale = new javax.swing.JTextField();
        textFieldTelephone = new javax.swing.JTextField();
        textFieldEmail = new javax.swing.JTextField();
        textFieldAdresse = new javax.swing.JTextField();
        textFieldSiret = new javax.swing.JTextField();
        labelAjouterAnnonceur = new javax.swing.JLabel();

        panelAnnonceur.setBackground(new java.awt.Color(153, 153, 153));

        buttonAjouterAnnonceur.setText("Ajouter ");
        buttonAjouterAnnonceur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterAnnonceurActionPerformed(evt);
            }
        });

        labelRaisonSociale.setText("Raison sociale");

        labelTelephone.setText("Telephone");

        labelEmail.setText("Email");

        labelAdresse.setText("Adresse");

        labelSiret.setText("Siret");

        javax.swing.GroupLayout panelAnnonceurLayout = new javax.swing.GroupLayout(panelAnnonceur);
        panelAnnonceur.setLayout(panelAnnonceurLayout);
        panelAnnonceurLayout.setHorizontalGroup(
            panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnnonceurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAnnonceurLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAjouterAnnonceur))
                    .addGroup(panelAnnonceurLayout.createSequentialGroup()
                        .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRaisonSociale)
                            .addComponent(labelTelephone)
                            .addComponent(labelEmail)
                            .addComponent(labelAdresse)
                            .addComponent(labelSiret))
                        .addGap(18, 18, 18)
                        .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldSiret)
                            .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textFieldTelephone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(textFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldRaisonSociale, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(textFieldAdresse))))
                .addGap(131, 131, 131))
        );
        panelAnnonceurLayout.setVerticalGroup(
            panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnnonceurLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRaisonSociale)
                    .addComponent(textFieldRaisonSociale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelephone)
                    .addComponent(textFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAdresse)
                    .addComponent(textFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSiret)
                    .addComponent(textFieldSiret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonAjouterAnnonceur)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        labelAjouterAnnonceur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAjouterAnnonceur.setText("Ajouter un annonceur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAjouterAnnonceur)
                        .addGap(161, 220, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelAnnonceur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelAjouterAnnonceur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAnnonceur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAjouterAnnonceurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterAnnonceurActionPerformed
        Societe s = new Societe();
        s.setRaisonSociale(textFieldRaisonSociale.getText());
        s.setTelephone(textFieldTelephone.getText());
        s.setMail(textFieldEmail.getText());
        s.setAdresse(textFieldAdresse.getText());
        s.setSiret(textFieldSiret.getText());
        
        try {
            SocieteDAO.creer(mainFrame.cnx, s);
            Annonceur a = new Annonceur(s.getId());
            AnnonceurDAO.creer(mainFrame.cnx, a);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(panelAnnonceur, ex.toString());
        }
        JOptionPane.showMessageDialog(panelAnnonceur, "L'ajout a réussi");
        this.dispose();
    }//GEN-LAST:event_buttonAjouterAnnonceurActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouterAnnonceurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouterAnnonceurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouterAnnonceurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouterAnnonceurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajouterAnnonceurFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjouterAnnonceur;
    private javax.swing.JLabel labelAdresse;
    private javax.swing.JLabel labelAjouterAnnonceur;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelRaisonSociale;
    private javax.swing.JLabel labelSiret;
    private javax.swing.JLabel labelTelephone;
    private javax.swing.JPanel panelAnnonceur;
    private javax.swing.JTextField textFieldAdresse;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldRaisonSociale;
    private javax.swing.JTextField textFieldSiret;
    private javax.swing.JTextField textFieldTelephone;
    // End of variables declaration//GEN-END:variables
}
