/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package megacasting.ihm;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import megacasting.dao.AnnonceurDAO;
import megacasting.dao.SocieteDAO;
import megacasting.entite.Annonceur;
import megacasting.entite.Societe;

/**
 *
 * @author MAXIME
 */
public class ajouterAnnonceurFrame extends javax.swing.JFrame {

    /**
     * Creates new form ajouterAnnonceurFrame
     */
    public ajouterAnnonceurFrame() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAnnonceur = new javax.swing.JPanel();
        buttonAjouterAnnonceur = new javax.swing.JButton();
        labelRaisonSociale = new javax.swing.JLabel();
        labelTelephone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelAdresse = new javax.swing.JLabel();
        labelSiret = new javax.swing.JLabel();
        textFieldRaisonSociale = new javax.swing.JTextField();
        textFieldTelephone = new javax.swing.JTextField();
        textFieldEmail = new javax.swing.JTextField();
        textFieldAdresse = new javax.swing.JTextField();
        textFieldSiret = new javax.swing.JTextField();
        labelErreurRaisonSociale = new javax.swing.JLabel();
        labelErreurTelephone = new javax.swing.JLabel();
        labelErreurEmail = new javax.swing.JLabel();
        labelErreurAdresse = new javax.swing.JLabel();
        labelErreurSiret = new javax.swing.JLabel();
        labelAjouterAnnonceur = new javax.swing.JLabel();

        panelAnnonceur.setBackground(new java.awt.Color(153, 153, 153));

        buttonAjouterAnnonceur.setText("Ajouter ");
        buttonAjouterAnnonceur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterAnnonceurActionPerformed(evt);
            }
        });

        labelRaisonSociale.setText("Raison sociale");

        labelTelephone.setText("Telephone");

        labelEmail.setText("Email");

        labelAdresse.setText("Adresse");

        labelSiret.setText("Siret");

        labelErreurRaisonSociale.setForeground(new java.awt.Color(255, 0, 0));

        labelErreurTelephone.setForeground(new java.awt.Color(255, 0, 0));

        labelErreurEmail.setForeground(new java.awt.Color(255, 0, 0));

        labelErreurAdresse.setForeground(new java.awt.Color(255, 0, 0));

        labelErreurSiret.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panelAnnonceurLayout = new javax.swing.GroupLayout(panelAnnonceur);
        panelAnnonceur.setLayout(panelAnnonceurLayout);
        panelAnnonceurLayout.setHorizontalGroup(
            panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnnonceurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAnnonceurLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAjouterAnnonceur)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAnnonceurLayout.createSequentialGroup()
                        .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRaisonSociale)
                            .addComponent(labelTelephone)
                            .addComponent(labelEmail)
                            .addComponent(labelAdresse)
                            .addComponent(labelSiret))
                        .addGap(18, 18, 18)
                        .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelErreurRaisonSociale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelErreurTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelAnnonceurLayout.createSequentialGroup()
                                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelErreurSiret)
                                        .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(textFieldRaisonSociale, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFieldEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textFieldTelephone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(textFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelErreurEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelErreurAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                                    .addComponent(textFieldSiret, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(26, 26, 26))
        );
        panelAnnonceurLayout.setVerticalGroup(
            panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnnonceurLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRaisonSociale)
                    .addComponent(textFieldRaisonSociale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErreurRaisonSociale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelephone)
                    .addComponent(textFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErreurTelephone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErreurEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAdresse)
                    .addComponent(textFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErreurAdresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSiret)
                    .addComponent(textFieldSiret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErreurSiret)
                .addGap(4, 4, 4)
                .addComponent(buttonAjouterAnnonceur)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        labelAjouterAnnonceur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAjouterAnnonceur.setText("Ajouter un annonceur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAjouterAnnonceur)
                        .addGap(161, 220, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelAnnonceur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelAjouterAnnonceur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAnnonceur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAjouterAnnonceurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterAnnonceurActionPerformed
        raz();
        
        List<Error> erreurs = verifFormulaire();
        
        if(erreurs.isEmpty()){
            Societe s = new Societe();
            s.setRaisonSociale(textFieldRaisonSociale.getText());
            s.setTelephone(textFieldTelephone.getText());
            s.setMail(textFieldEmail.getText());
            s.setAdresse(textFieldAdresse.getText());
            s.setSiret(textFieldSiret.getText());
        
            try {
                SocieteDAO.creer(mainFrame.cnx, s);
                Annonceur a = new Annonceur(s.getId());
                AnnonceurDAO.creer(mainFrame.cnx, a);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(panelAnnonceur, ex.toString());
            }
            JOptionPane.showMessageDialog(panelAnnonceur, "L'ajout a réussi");
            this.dispose();
        }else{
            affichageErreurs(erreurs);
        }
    }//GEN-LAST:event_buttonAjouterAnnonceurActionPerformed
   
    private void raz(){
        labelErreurRaisonSociale.setText(null);
        labelErreurTelephone.setText(null);
        labelErreurEmail.setText(null);
        labelErreurAdresse.setText(null);
        labelErreurSiret.setText(null);
    }
    
    private void affichageErreurs(List<Error> erreurs){
        for(Error e : erreurs){
            switch(e){
                case raisonSocialeVide : 
                    this.labelErreurRaisonSociale.setText("Veuillez saisir une raison sociale");
                    break;
                case telephoneVide : 
                    this.labelErreurTelephone.setText("Veuillez saisir un numéro de telephone");
                    break;
                case telephoneInvalide : 
                    this.labelErreurTelephone.setText("Veuillez saisir un numéro de telephone valide");
                    break;
                case emailVide : 
                    this.labelErreurEmail.setText("Veuillez saisir une adresse email");
                    break;
                case emailInvalide : 
                    this.labelErreurEmail.setText("Veuillez saisir une adresse email valide");
                    break;
                case adresseVide : 
                    this.labelErreurAdresse.setText("Veuillez saisir une adresse");
                    break;
                case siretVide : 
                    this.labelErreurSiret.setText("Veuillez saisir un numéro de siret");
                    break;
                case siretInvalide : 
                    this.labelErreurSiret.setText("Veuillez saisir un numéro de siret valide");
                    break;
            }
        }
    }
    
    private enum Error{
        raisonSocialeVide,telephoneVide,telephoneInvalide,emailVide,emailInvalide,
        adresseVide,adresseInvalide,siretVide,siretInvalide;
    }
    
    private List verifFormulaire(){
        List<Error> erreurs = new ArrayList();
        
        if(textFieldRaisonSociale.getText().equals("")){
            erreurs.add(Error.raisonSocialeVide);
        }
        
        if(textFieldTelephone.getText().equals("")){
            erreurs.add(Error.telephoneVide);
        }else{
            if(!regexTelephone(textFieldTelephone.getText())){
                erreurs.add(Error.telephoneInvalide);
            }
            
        }
        
        if(textFieldEmail.getText().equals("")){
            erreurs.add(Error.emailVide);
        }else{
            if(!regexEmail(textFieldEmail.getText())){
                erreurs.add(Error.emailInvalide);
            }
        }
        
        if(textFieldAdresse.getText().equals("")){
            erreurs.add(Error.adresseVide);
        }
        
        if(textFieldSiret.getText().equals("")){
            erreurs.add(Error.siretVide);
        }else{
            if(!regexSiret(textFieldSiret.getText())){
                erreurs.add(Error.siretInvalide);
            }
        }
        return erreurs;
    }
    
    private boolean regexTelephone(String telephone){
        Pattern pattern = Pattern.compile("^0[1-68][0-9]{8}$");
        Matcher m = pattern.matcher(telephone);
        boolean b = m.matches();
        
        return b;
    }
    
    private boolean regexEmail(String email){
        Pattern pattern = Pattern.compile("^[a-z0-9._-]+@[a-z0-9._-]{2,}\\.[a-z]{2,4}$");
        Matcher m = pattern.matcher(email);
        boolean b = m.matches();
        
        return b;
    }
    
    private boolean regexSiret(String siret){
        Pattern pattern = Pattern.compile("^[0-9]{14}$");
        Matcher m = pattern.matcher(siret);
        boolean b = m.matches();
        
        return b;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouterAnnonceurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouterAnnonceurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouterAnnonceurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouterAnnonceurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajouterAnnonceurFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjouterAnnonceur;
    private javax.swing.JLabel labelAdresse;
    private javax.swing.JLabel labelAjouterAnnonceur;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelErreurAdresse;
    private javax.swing.JLabel labelErreurEmail;
    private javax.swing.JLabel labelErreurRaisonSociale;
    private javax.swing.JLabel labelErreurSiret;
    private javax.swing.JLabel labelErreurTelephone;
    private javax.swing.JLabel labelRaisonSociale;
    private javax.swing.JLabel labelSiret;
    private javax.swing.JLabel labelTelephone;
    private javax.swing.JPanel panelAnnonceur;
    private javax.swing.JTextField textFieldAdresse;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldRaisonSociale;
    private javax.swing.JTextField textFieldSiret;
    private javax.swing.JTextField textFieldTelephone;
    // End of variables declaration//GEN-END:variables
}
