/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package megacasting.ihm;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import megacasting.dao.AnnonceurDAO;
import megacasting.dao.DiffuseurDAO;
import megacasting.dao.OffreDAO;
import megacasting.dao.SocieteDAO;
import megacasting.entite.Annonceur;
import megacasting.entite.Diffuseur;
import megacasting.entite.Offre;
import megacasting.entite.Societe;

/**
 *
 * @author ihamel
 */
public class societeFrame extends javax.swing.JFrame {

    /**
     * Creates new form societeFrame
     */
    public societeFrame() {
        initComponents();
        refreshListAnnonceur();
        refreshListDiffuseur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDiffuseur = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDiffuseur = new javax.swing.JList();
        labelDiffuseurs = new javax.swing.JLabel();
        labelRaisonSocialeDiffuseur = new javax.swing.JLabel();
        labelTelephoneDiffuseur = new javax.swing.JLabel();
        labelEmailDiffuseur = new javax.swing.JLabel();
        labelAdresseDiffuseur = new javax.swing.JLabel();
        labelSiretDiffuseur = new javax.swing.JLabel();
        textFieldRaisonSocialeDiffuseur = new javax.swing.JTextField();
        textFieldTelephoneDiffuseur = new javax.swing.JTextField();
        textFieldEmailDiffuseur = new javax.swing.JTextField();
        textFieldAdresseDiffuseur = new javax.swing.JTextField();
        textFieldSiretDiffuseur = new javax.swing.JTextField();
        buttonModifierDiffuseur = new javax.swing.JButton();
        buttonSupprimerDiffuseur = new javax.swing.JButton();
        buttonAjouterDiffuseur = new javax.swing.JButton();
        labelErreurRaisonSocialeDiffuseur = new javax.swing.JLabel();
        labelErreurTelephoneDiffuseur = new javax.swing.JLabel();
        labelErreurEmailDiffuseur = new javax.swing.JLabel();
        labelErreurAdresseDiffuseur = new javax.swing.JLabel();
        labelErreurSiretDiffuseur = new javax.swing.JLabel();
        labelGestionSociete = new javax.swing.JLabel();
        panelAnnonceur = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listAnnonceur = new javax.swing.JList();
        labelAnnonceurs = new javax.swing.JLabel();
        labelRaisonSocialeAnnonceur = new javax.swing.JLabel();
        labelTelephoneAnnonceur = new javax.swing.JLabel();
        labelEmailAnnonceur = new javax.swing.JLabel();
        labelAdresseAnnonceur = new javax.swing.JLabel();
        labelSiretAnnonceur = new javax.swing.JLabel();
        textFieldRaisonSocialeAnnonceur = new javax.swing.JTextField();
        textFieldTelephoneAnnonceur = new javax.swing.JTextField();
        textFieldEmailAnnonceur = new javax.swing.JTextField();
        textFieldAdresseAnnonceur = new javax.swing.JTextField();
        textFieldSiretAnnonceur = new javax.swing.JTextField();
        buttonModifierAnnonceur = new javax.swing.JButton();
        buttonSupprimerAnnonceur = new javax.swing.JButton();
        buttonAjouterAnnonceur = new javax.swing.JButton();
        labelErreurRaisonSocialeAnnonceur = new javax.swing.JLabel();
        labelErreurTelephoneAnnonceur = new javax.swing.JLabel();
        labelErreurEmailAnnonceur = new javax.swing.JLabel();
        labelErreurAdresseAnnonceur = new javax.swing.JLabel();
        labelErreurSiretAnnonceur = new javax.swing.JLabel();

        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        panelDiffuseur.setBackground(new java.awt.Color(153, 153, 153));

        listDiffuseur.setBorder(new javax.swing.border.MatteBorder(null));
        listDiffuseur.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listDiffuseurValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listDiffuseur);

        labelDiffuseurs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDiffuseurs.setText("Diffuseurs");

        labelRaisonSocialeDiffuseur.setText("Raison Sociale");

        labelTelephoneDiffuseur.setText("Telephone");

        labelEmailDiffuseur.setText("Email");

        labelAdresseDiffuseur.setText("Adresse");

        labelSiretDiffuseur.setText("Siret");

        buttonModifierDiffuseur.setText("Enregistrer");
        buttonModifierDiffuseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifierDiffuseurActionPerformed(evt);
            }
        });

        buttonSupprimerDiffuseur.setText("Supprimer");
        buttonSupprimerDiffuseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupprimerDiffuseurActionPerformed(evt);
            }
        });

        buttonAjouterDiffuseur.setText("Ajouter un diffuseur");
        buttonAjouterDiffuseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterDiffuseurActionPerformed(evt);
            }
        });

        labelErreurRaisonSocialeDiffuseur.setForeground(new java.awt.Color(255, 0, 0));

        labelErreurTelephoneDiffuseur.setForeground(new java.awt.Color(255, 0, 0));

        labelErreurEmailDiffuseur.setForeground(new java.awt.Color(255, 0, 0));

        labelErreurAdresseDiffuseur.setForeground(new java.awt.Color(255, 0, 0));

        labelErreurSiretDiffuseur.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panelDiffuseurLayout = new javax.swing.GroupLayout(panelDiffuseur);
        panelDiffuseur.setLayout(panelDiffuseurLayout);
        panelDiffuseurLayout.setHorizontalGroup(
            panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiffuseurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDiffuseurs)
                    .addGroup(panelDiffuseurLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRaisonSocialeDiffuseur)
                            .addComponent(labelTelephoneDiffuseur)
                            .addComponent(labelEmailDiffuseur)
                            .addComponent(labelAdresseDiffuseur)
                            .addComponent(labelSiretDiffuseur))
                        .addGap(18, 18, 18)
                        .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldSiretDiffuseur, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(textFieldAdresseDiffuseur)
                            .addComponent(labelErreurRaisonSocialeDiffuseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelErreurTelephoneDiffuseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelErreurEmailDiffuseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelErreurAdresseDiffuseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelErreurSiretDiffuseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldRaisonSocialeDiffuseur)
                            .addComponent(textFieldTelephoneDiffuseur)
                            .addComponent(textFieldEmailDiffuseur)))
                    .addGroup(panelDiffuseurLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(buttonSupprimerDiffuseur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonModifierDiffuseur)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAjouterDiffuseur)
                .addGap(26, 26, 26))
        );
        panelDiffuseurLayout.setVerticalGroup(
            panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiffuseurLayout.createSequentialGroup()
                .addComponent(labelDiffuseurs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDiffuseurLayout.createSequentialGroup()
                        .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRaisonSocialeDiffuseur)
                            .addComponent(textFieldRaisonSocialeDiffuseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelErreurRaisonSocialeDiffuseur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelephoneDiffuseur)
                            .addComponent(textFieldTelephoneDiffuseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelErreurTelephoneDiffuseur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmailDiffuseur)
                            .addComponent(textFieldEmailDiffuseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAjouterDiffuseur))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelErreurEmailDiffuseur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAdresseDiffuseur)
                            .addComponent(textFieldAdresseDiffuseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelErreurAdresseDiffuseur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSiretDiffuseur)
                            .addComponent(textFieldSiretDiffuseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDiffuseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDiffuseurLayout.createSequentialGroup()
                        .addComponent(labelErreurSiretDiffuseur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(buttonModifierDiffuseur))
                    .addComponent(buttonSupprimerDiffuseur))
                .addContainerGap())
        );

        labelGestionSociete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelGestionSociete.setText("Gestion des sociétés");

        panelAnnonceur.setBackground(new java.awt.Color(153, 153, 153));

        listAnnonceur.setBorder(new javax.swing.border.MatteBorder(null));
        listAnnonceur.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listAnnonceurValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listAnnonceur);

        labelAnnonceurs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAnnonceurs.setText("Annonceurs");

        labelRaisonSocialeAnnonceur.setText("Raison Sociale");

        labelTelephoneAnnonceur.setText("Telephone");

        labelEmailAnnonceur.setText("Email");

        labelAdresseAnnonceur.setText("Adresse");

        labelSiretAnnonceur.setText("Siret");

        buttonModifierAnnonceur.setText("Enregistrer");
        buttonModifierAnnonceur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifierAnnonceurActionPerformed(evt);
            }
        });

        buttonSupprimerAnnonceur.setText("Supprimer");
        buttonSupprimerAnnonceur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupprimerAnnonceurActionPerformed(evt);
            }
        });

        buttonAjouterAnnonceur.setText("Ajouter un annonceur");
        buttonAjouterAnnonceur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterAnnonceurActionPerformed(evt);
            }
        });

        labelErreurRaisonSocialeAnnonceur.setForeground(new java.awt.Color(255, 0, 0));

        labelErreurTelephoneAnnonceur.setForeground(new java.awt.Color(255, 0, 0));

        labelErreurEmailAnnonceur.setForeground(new java.awt.Color(255, 0, 0));

        labelErreurAdresseAnnonceur.setForeground(new java.awt.Color(255, 0, 0));

        labelErreurSiretAnnonceur.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panelAnnonceurLayout = new javax.swing.GroupLayout(panelAnnonceur);
        panelAnnonceur.setLayout(panelAnnonceurLayout);
        panelAnnonceurLayout.setHorizontalGroup(
            panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnnonceurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelAnnonceurs)
                    .addGroup(panelAnnonceurLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRaisonSocialeAnnonceur)
                            .addComponent(labelTelephoneAnnonceur)
                            .addComponent(labelEmailAnnonceur)
                            .addComponent(labelAdresseAnnonceur)
                            .addComponent(labelSiretAnnonceur))
                        .addGap(18, 18, 18)
                        .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldAdresseAnnonceur, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(textFieldEmailAnnonceur)
                            .addComponent(textFieldTelephoneAnnonceur)
                            .addComponent(textFieldRaisonSocialeAnnonceur)
                            .addComponent(labelErreurRaisonSocialeAnnonceur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelErreurTelephoneAnnonceur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelErreurEmailAnnonceur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelErreurAdresseAnnonceur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelErreurSiretAnnonceur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldSiretAnnonceur)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnnonceurLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(buttonSupprimerAnnonceur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonModifierAnnonceur)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(buttonAjouterAnnonceur)
                .addContainerGap())
        );
        panelAnnonceurLayout.setVerticalGroup(
            panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnnonceurLayout.createSequentialGroup()
                .addComponent(labelAnnonceurs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAnnonceurLayout.createSequentialGroup()
                        .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRaisonSocialeAnnonceur)
                            .addComponent(textFieldRaisonSocialeAnnonceur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelErreurRaisonSocialeAnnonceur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelephoneAnnonceur)
                            .addComponent(textFieldTelephoneAnnonceur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelErreurTelephoneAnnonceur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmailAnnonceur)
                            .addComponent(textFieldEmailAnnonceur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAjouterAnnonceur))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelErreurEmailAnnonceur)
                        .addGap(2, 2, 2)
                        .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAdresseAnnonceur)
                            .addComponent(textFieldAdresseAnnonceur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAnnonceurLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(labelSiretAnnonceur))
                            .addGroup(panelAnnonceurLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelErreurAdresseAnnonceur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldSiretAnnonceur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelErreurSiretAnnonceur))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAnnonceurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonModifierAnnonceur)
                    .addComponent(buttonSupprimerAnnonceur))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelGestionSociete, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 581, Short.MAX_VALUE))
                    .addComponent(panelDiffuseur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelAnnonceur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelGestionSociete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                .addComponent(panelDiffuseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(panelAnnonceur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(375, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listDiffuseurValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listDiffuseurValueChanged
        Societe s = (Societe) listDiffuseur.getSelectedValue();

        if (s != null) {
            textFieldRaisonSocialeDiffuseur.setText(s.getRaisonSociale());
            textFieldTelephoneDiffuseur.setText(s.getTelephone());
            textFieldEmailDiffuseur.setText(s.getMail());
            textFieldAdresseDiffuseur.setText(s.getAdresse());
            textFieldSiretDiffuseur.setText(s.getSiret());
        }
    }//GEN-LAST:event_listDiffuseurValueChanged

    private void buttonModifierDiffuseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifierDiffuseurActionPerformed
        raz();
        Societe s = (Societe) listDiffuseur.getSelectedValue();

        List<Error> erreursDiffuseur = verifFormulaireDiffuseur();

        if (erreursDiffuseur.isEmpty()) {

            s.setRaisonSociale(textFieldRaisonSocialeDiffuseur.getText());
            s.setTelephone(textFieldTelephoneDiffuseur.getText());
            s.setMail(textFieldEmailDiffuseur.getText());
            s.setAdresse(textFieldAdresseDiffuseur.getText());
            s.setSiret(textFieldSiretDiffuseur.getText());

            try {
                SocieteDAO.modifier(mainFrame.cnx, s);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(panelDiffuseur, ex.toString());
            }
            JOptionPane.showMessageDialog(panelDiffuseur, "La modification à réussie");
            refreshListDiffuseur(listDiffuseur.getSelectedIndex());
        } else {
            affichageErreursDiffuseur(erreursDiffuseur);
        }
    }//GEN-LAST:event_buttonModifierDiffuseurActionPerformed

    private void buttonSupprimerDiffuseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupprimerDiffuseurActionPerformed
        Societe s = (Societe) listDiffuseur.getSelectedValue();
        Diffuseur d = DiffuseurDAO.trouver(mainFrame.cnx, s.getId());

        if (d != null) {
            try {
                SocieteDAO.supprimer(mainFrame.cnx, s);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(panelDiffuseur, ex.toString());
            }
            JOptionPane.showMessageDialog(panelDiffuseur, "La suppression a réussie");
            refreshListDiffuseur();
        } else {
            JOptionPane.showMessageDialog(panelDiffuseur, "Le diffuseur n'existe pas");
        }
    }//GEN-LAST:event_buttonSupprimerDiffuseurActionPerformed

    private void buttonAjouterDiffuseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterDiffuseurActionPerformed
        new ajouterDiffuseurFrame().setVisible(true);
    }//GEN-LAST:event_buttonAjouterDiffuseurActionPerformed

    private void listAnnonceurValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listAnnonceurValueChanged
        Societe s = (Societe) listAnnonceur.getSelectedValue();

        if (s != null) {
            textFieldRaisonSocialeAnnonceur.setText(s.getRaisonSociale());
            textFieldTelephoneAnnonceur.setText(s.getTelephone());
            textFieldEmailAnnonceur.setText(s.getMail());
            textFieldAdresseAnnonceur.setText(s.getAdresse());
            textFieldSiretAnnonceur.setText(s.getSiret());
        }

    }//GEN-LAST:event_listAnnonceurValueChanged

    private void buttonModifierAnnonceurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifierAnnonceurActionPerformed
        raz();
        Societe s = (Societe) listAnnonceur.getSelectedValue();

        List<Error> erreursAnnonceur = verifFormulaireAnnonceur();

        if (erreursAnnonceur.isEmpty()) {
            s.setRaisonSociale(textFieldRaisonSocialeAnnonceur.getText());
            s.setTelephone(textFieldTelephoneAnnonceur.getText());
            s.setMail(textFieldEmailAnnonceur.getText());
            s.setAdresse(textFieldAdresseAnnonceur.getText());
            s.setSiret(textFieldSiretAnnonceur.getText());

            try {
                SocieteDAO.modifier(mainFrame.cnx, s);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(panelAnnonceur, ex.toString());
            }
            JOptionPane.showMessageDialog(panelAnnonceur, "La modification à réussie");
            refreshListAnnonceur(listAnnonceur.getSelectedIndex());
        } else {
            affichageErreursAnnonceur(erreursAnnonceur);
        }
    }//GEN-LAST:event_buttonModifierAnnonceurActionPerformed

    private void buttonSupprimerAnnonceurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupprimerAnnonceurActionPerformed
        Societe s = (Societe) listAnnonceur.getSelectedValue();
        Annonceur a = AnnonceurDAO.trouver(mainFrame.cnx, s.getId());

        if (a != null) {
            int retour = JOptionPane.showConfirmDialog(panelAnnonceur, "Êtes vous sur de vouloir supprimer l'annonceur et les offres qui y sont associées?", "Attention", JOptionPane.YES_NO_OPTION);
            if (retour == 0) {
                List<Offre> loffre = OffreDAO.lister(mainFrame.cnx);
                for (Offre o : loffre) {
                    if (a.getId() == o.getIdAnnonceur()) {
                        try {
                            OffreDAO.supprimer(mainFrame.cnx, o);
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                    }
                }
                try {
                    SocieteDAO.supprimer(mainFrame.cnx, s);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(panelDiffuseur, ex.toString());
                }
                JOptionPane.showMessageDialog(panelAnnonceur, "La suppression a réussie");
                refreshListAnnonceur();
            }
        } else {
            JOptionPane.showMessageDialog(panelAnnonceur, "L'annonceur n'existe pas");
        }
    }//GEN-LAST:event_buttonSupprimerAnnonceurActionPerformed

    private void buttonAjouterAnnonceurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterAnnonceurActionPerformed
        new ajouterAnnonceurFrame().setVisible(true);
    }//GEN-LAST:event_buttonAjouterAnnonceurActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        refreshListAnnonceur();
        refreshListDiffuseur();
    }//GEN-LAST:event_formWindowGainedFocus

    private void refreshListAnnonceur() {
        refreshListAnnonceur(0);
    }

    private void refreshListAnnonceur(int selectedIndex) {
        DefaultListModel listModelAnnonceur = null;

        if (listDiffuseur.getModel() instanceof DefaultListModel) {
            listModelAnnonceur = (DefaultListModel) listAnnonceur.getModel();
            listModelAnnonceur.setSize(0);
        } else {
            listModelAnnonceur = new DefaultListModel();
            listAnnonceur.setModel(listModelAnnonceur);
        }

        List<Annonceur> lannonceurs = AnnonceurDAO.lister(mainFrame.cnx);

        for (Annonceur a : lannonceurs) {
            int idAnnonceur = a.getId();
            Societe s = SocieteDAO.trouver(mainFrame.cnx, idAnnonceur);
            if (s != null) {
                listModelAnnonceur.addElement(s);
            }
        }

        if (listModelAnnonceur.getSize() > 0) {
            listAnnonceur.setSelectedIndex(selectedIndex);
        }
    }

    private void refreshListDiffuseur() {
        refreshListDiffuseur(0);
    }

    private void refreshListDiffuseur(int selectedIndex) {
        DefaultListModel listModelDiffuseur = null;

        if (listDiffuseur.getModel() instanceof DefaultListModel) {
            listModelDiffuseur = (DefaultListModel) listDiffuseur.getModel();
            listModelDiffuseur.setSize(0);
        } else {
            listModelDiffuseur = new DefaultListModel();
            listDiffuseur.setModel(listModelDiffuseur);
        }

        List<Diffuseur> ldiffuseurs = DiffuseurDAO.lister(mainFrame.cnx);

        for (Diffuseur d : ldiffuseurs) {
            int idDiffuseur = d.getId();
            Societe s = SocieteDAO.trouver(mainFrame.cnx, idDiffuseur);
            if (s != null) {
                listModelDiffuseur.addElement(s);
            }
        }

        if (listModelDiffuseur.getSize() > 0) {
            listDiffuseur.setSelectedIndex(selectedIndex);
        }
    }

    private enum Error {

        raisonSocialeVide, telephoneVide, telephoneInvalide, emailVide, emailInvalide, adresseVide, siretVide, siretInvalide;
    }

    private void raz() {
        //Annonceur
        labelErreurRaisonSocialeAnnonceur.setText(null);
        labelErreurTelephoneAnnonceur.setText(null);
        labelErreurEmailAnnonceur.setText(null);
        labelErreurAdresseAnnonceur.setText(null);
        labelErreurSiretAnnonceur.setText(null);
        //Diffuseur
        labelErreurRaisonSocialeDiffuseur.setText(null);
        labelErreurTelephoneDiffuseur.setText(null);
        labelErreurEmailDiffuseur.setText(null);
        labelErreurAdresseDiffuseur.setText(null);
        labelErreurSiretDiffuseur.setText(null);
    }

    private List verifFormulaireAnnonceur() {
        List<Error> erreursAnnonceur = new ArrayList();

        if (textFieldRaisonSocialeAnnonceur.getText().equals("")) {
            erreursAnnonceur.add(Error.raisonSocialeVide);
        }

        if (textFieldTelephoneAnnonceur.getText().equals("")) {
            erreursAnnonceur.add(Error.telephoneVide);
        } else {
            if (!regexTelephone(textFieldTelephoneAnnonceur.getText())) {
                erreursAnnonceur.add(Error.telephoneInvalide);
            }
        }

        if (textFieldEmailAnnonceur.getText().equals("")) {
            erreursAnnonceur.add(Error.emailVide);
        } else {
            if (!regexEmail(textFieldEmailAnnonceur.getText())) {
                erreursAnnonceur.add(Error.emailInvalide);
            }
        }

        if (textFieldAdresseAnnonceur.getText().equals("")) {
            erreursAnnonceur.add(Error.adresseVide);
        }

        if (textFieldSiretAnnonceur.getText().equals("")) {
            erreursAnnonceur.add(Error.siretVide);
        } else {
            if (!regexSiret(textFieldSiretAnnonceur.getText())) {
                erreursAnnonceur.add(Error.siretInvalide);
            }
        }
        return erreursAnnonceur;
    }

    private List verifFormulaireDiffuseur() {
        List<Error> erreursDiffuseur = new ArrayList();

        if (textFieldRaisonSocialeDiffuseur.getText().equals("")) {
            erreursDiffuseur.add(Error.raisonSocialeVide);
        }

        if (textFieldTelephoneDiffuseur.getText().equals("")) {
            erreursDiffuseur.add(Error.telephoneVide);
        } else {
            if (!regexTelephone(textFieldTelephoneDiffuseur.getText())) {
                erreursDiffuseur.add(Error.telephoneInvalide);
            }
        }

        if (textFieldEmailDiffuseur.getText().equals("")) {
            erreursDiffuseur.add(Error.emailVide);
        } else {
            if (!regexEmail(textFieldEmailDiffuseur.getText())) {
                erreursDiffuseur.add(Error.emailInvalide);
            }
        }

        if (textFieldAdresseDiffuseur.getText().equals("")) {
            erreursDiffuseur.add(Error.adresseVide);
        }

        if (textFieldSiretDiffuseur.getText().equals("")) {
            erreursDiffuseur.add(Error.siretVide);
        } else {
            if (!regexSiret(textFieldSiretDiffuseur.getText())) {
                erreursDiffuseur.add(Error.siretInvalide);
            }
        }
        return erreursDiffuseur;
    }

    private void affichageErreursAnnonceur(List<Error> erreursAnnonceur) {
        for (Error e : erreursAnnonceur) {
            switch (e) {
                case raisonSocialeVide:
                    this.labelErreurRaisonSocialeAnnonceur.setText("Veuillez saisir une raison sociale");
                    break;
                case telephoneVide:
                    this.labelErreurTelephoneAnnonceur.setText("Veuillez saisir un numéro de telephone");
                    break;
                case telephoneInvalide:
                    this.labelErreurTelephoneAnnonceur.setText("Veuillez saisir un numéro de telephone valide");
                    break;
                case emailVide:
                    this.labelErreurEmailAnnonceur.setText("Veuillez saisir une adresse email");
                    break;
                case emailInvalide:
                    this.labelErreurEmailAnnonceur.setText("Veuillez saisir une adresse email valide");
                    break;
                case adresseVide:
                    this.labelErreurAdresseAnnonceur.setText("Veuillez saisir une adresse");
                    break;
                case siretVide:
                    this.labelErreurSiretAnnonceur.setText("Veuillez saisir un numéro de siret");
                    break;
                case siretInvalide:
                    this.labelErreurSiretAnnonceur.setText("Veuillez saisir un numéro de siret valide");
                    break;
            }
        }
    }

    private void affichageErreursDiffuseur(List<Error> erreursDiffuseur) {
        for (Error e : erreursDiffuseur) {
            switch (e) {
                case raisonSocialeVide:
                    this.labelErreurRaisonSocialeDiffuseur.setText("Veuillez saisir une raison sociale");
                    break;
                case telephoneVide:
                    this.labelErreurTelephoneDiffuseur.setText("Veuillez saisir un numéro de telephone");
                    break;
                case telephoneInvalide:
                    this.labelErreurTelephoneDiffuseur.setText("Veuillez saisir un numéro de telephone valide");
                    break;
                case emailVide:
                    this.labelErreurEmailDiffuseur.setText("Veuillez saisir une adresse email");
                    break;
                case emailInvalide:
                    this.labelErreurEmailDiffuseur.setText("Veuillez saisir une adresse email valide");
                    break;
                case adresseVide:
                    this.labelErreurAdresseDiffuseur.setText("Veuillez saisir une adresse");
                    break;
                case siretVide:
                    this.labelErreurSiretDiffuseur.setText("Veuillez saisir un numéro de siret");
                    break;
                case siretInvalide:
                    this.labelErreurSiretDiffuseur.setText("Veuillez saisir un numéro de siret valide");
                    break;
            }
        }
    }

    private boolean regexTelephone(String telephone) {
        Pattern pattern = Pattern.compile("^0[1-68][0-9]{8}$");
        Matcher m = pattern.matcher(telephone);
        boolean b = m.matches();

        return b;
    }

    private boolean regexEmail(String email) {
        Pattern pattern = Pattern.compile("^[a-z0-9._-]+@[a-z0-9._-]{2,}\\.[a-z]{2,4}$");
        Matcher m = pattern.matcher(email);
        boolean b = m.matches();

        return b;
    }

    private boolean regexSiret(String siret) {
        Pattern pattern = Pattern.compile("^[0-9]{14}$");
        Matcher m = pattern.matcher(siret);
        boolean b = m.matches();

        return b;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(societeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(societeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(societeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(societeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new societeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjouterAnnonceur;
    private javax.swing.JButton buttonAjouterDiffuseur;
    private javax.swing.JButton buttonModifierAnnonceur;
    private javax.swing.JButton buttonModifierDiffuseur;
    private javax.swing.JButton buttonSupprimerAnnonceur;
    private javax.swing.JButton buttonSupprimerDiffuseur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAdresseAnnonceur;
    private javax.swing.JLabel labelAdresseDiffuseur;
    private javax.swing.JLabel labelAnnonceurs;
    private javax.swing.JLabel labelDiffuseurs;
    private javax.swing.JLabel labelEmailAnnonceur;
    private javax.swing.JLabel labelEmailDiffuseur;
    private javax.swing.JLabel labelErreurAdresseAnnonceur;
    private javax.swing.JLabel labelErreurAdresseDiffuseur;
    private javax.swing.JLabel labelErreurEmailAnnonceur;
    private javax.swing.JLabel labelErreurEmailDiffuseur;
    private javax.swing.JLabel labelErreurRaisonSocialeAnnonceur;
    private javax.swing.JLabel labelErreurRaisonSocialeDiffuseur;
    private javax.swing.JLabel labelErreurSiretAnnonceur;
    private javax.swing.JLabel labelErreurSiretDiffuseur;
    private javax.swing.JLabel labelErreurTelephoneAnnonceur;
    private javax.swing.JLabel labelErreurTelephoneDiffuseur;
    private javax.swing.JLabel labelGestionSociete;
    private javax.swing.JLabel labelRaisonSocialeAnnonceur;
    private javax.swing.JLabel labelRaisonSocialeDiffuseur;
    private javax.swing.JLabel labelSiretAnnonceur;
    private javax.swing.JLabel labelSiretDiffuseur;
    private javax.swing.JLabel labelTelephoneAnnonceur;
    private javax.swing.JLabel labelTelephoneDiffuseur;
    private javax.swing.JList listAnnonceur;
    private javax.swing.JList listDiffuseur;
    private javax.swing.JPanel panelAnnonceur;
    private javax.swing.JPanel panelDiffuseur;
    private javax.swing.JTextField textFieldAdresseAnnonceur;
    private javax.swing.JTextField textFieldAdresseDiffuseur;
    private javax.swing.JTextField textFieldEmailAnnonceur;
    private javax.swing.JTextField textFieldEmailDiffuseur;
    private javax.swing.JTextField textFieldRaisonSocialeAnnonceur;
    private javax.swing.JTextField textFieldRaisonSocialeDiffuseur;
    private javax.swing.JTextField textFieldSiretAnnonceur;
    private javax.swing.JTextField textFieldSiretDiffuseur;
    private javax.swing.JTextField textFieldTelephoneAnnonceur;
    private javax.swing.JTextField textFieldTelephoneDiffuseur;
    // End of variables declaration//GEN-END:variables
}
